version: '3'
services:
  mysql:
      image: mysql:latest
      env_file: .env_mysql
      ports:
        - 127.0.0.1:3306:3306
      restart: on-failure
      networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_production_app
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - mynetwork
  
  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    env_file: bot/.env
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - mynetwork

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/static
    ports:
      - 80:80
    depends_on:
      - app
    restart: on-failure
    networks:
      - mynetwork

networks:
  mynetwork: